### ISSUE TITLE
[Linux/arm64.deb] Cannot load Example

### ISSUE THREAD

**Issue by upost** [textbrowser/glitch#10]
When trying to load Arduino-Blink.db, I get:

An error occurred while processing the file /opt/glitch/Examples/Arduino/Arduino-Blink.db. (Empty diagram name.)

Same for some others I tried.

[same version and system as in my other issue]

**Comment by textbrowser** [comment]
There's and ARM64 version?

**Comment by textbrowser** [comment]
Perhaps the error is too dramatic. I'll relax it. Will you be able to rebuild and test?

**Comment by textbrowser** [comment]
A yup. Copy the files to your home.

sqlite3 Examples/Arduino/Arduino-Blink.db 
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
sqlite> select name from diagram;
Error: in prepare, attempt to write a readonly database (8)
sqlite>

**Comment by textbrowser** [comment]
I'll add a README but otherwise I cannot resolve it because we don't want writable files owned by root.

**Comment by textbrowser** [comment]
Completed.

**Comment by upost** [comment]
If you could provide build instruction I am able to understand, I'd like to checkout the branch and give it a try

**Comment by textbrowser** [comment]
Install the Qt development suite; minimum Qt 5.15 LTS. See one of the DEBIAN/control files for hints.

> qmake -o Makefile
> make -j $(nproc)

Or use the current version you have and copy the Examples directory onto your desktop.
