### ISSUE TITLE
Failing to build project...

### ISSUE THREAD

**Issue by MythicalForce** [textbrowser/glitch#5]
trying to build a Qt project but getting
```
09:44:25: The process "C:\Qt\Tools\mingw1120_64\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project glitch (kit: Desktop Qt 7.0.2 MinGW 64-bit (Use This))
When executing step "Make"
```
```
:-1: error: No rule to make target 'UI/Arduino/glitch-object-flow-control-arduino.ui', needed by 'temp/ui/ui_glitch-object-flow-control-arduino.h'.  Stop.
```

**Comment by textbrowser** [comment]
File missing from the repository. Try now.

**Comment by MythicalForce** [comment]
There we go :) im not gonna say what you should do with your project! but i have been looking for a kind of "Blueprint system" like Unreal-Engine has! i would LOVE to code with a system like that! (i code in C++) but have been using the BP system of UE for years and just LOVE how it works and the workflow!

![BPQS_6_Step4 1](https://user-images.githubusercontent.com/62886250/178484920-98196a8f-a2a7-4a38-a07c-820ffbc1044d.png)

**Comment by textbrowser** [comment]
https://raw.githubusercontent.com/textbrowser/glitch/master/Images/glitch-1.png

That's the state of Glitch so far. This other system depicted in your image uses heavy styling. Glitch includes styling, but I'm not at that phase. One of the problems I'm encountering is compactness of diagrams. I intend to address that through the ability of resizing objects. I see this system uses curved connections (wires). I'm using poly-lines.

I'm working through Arduino's examples. The current examples in the repository are generated from Glitch.

**Comment by textbrowser** [comment]
I have single input and output ports. For example, a function may have 10 inputs. 10 input ports are difficult to represent on a component. However, 10 wires are clear. There is also ordering providing by Glitch. The order of the objects describes the order in the generated source.

**Comment by textbrowser** [comment]
And please submit any preference and we'll see if it can be met.

**Comment by textbrowser** [comment]
Added curves as wire types. Optional for the future.

**Comment by textbrowser** [comment]
And Glitch is for Arduino, however, it can be extended for other languages and projects. The extension requires much work, however, because one has to create objects and their behaviors.

**Comment by MythicalForce** [comment]
> And Glitch is for Arduino, however, it can be extended for other languages and projects. The extension requires much work, however, because one has to create objects and their behaviors.

yes i was thinking for Arduino! as Unreal Engine BP system is for C++ (game dev) ONLY!! i wish it was for Arduino! that is why i wish it to be much like that BP system

**Comment by textbrowser** [comment]
Did you see the progress in Glitch? I'll produce some video tutorials when I can. Styles can achieve a lot of those nifty appearances. I'm not particularly fond of styles as they have to be verified in Mac, Windows, and the assortment of Linux distributions. My first goal is to support 90% - 100% of the Arduino language. Then preferences and styles and other interesting things. The TO-DO shows the progress. Glitch has to be an editor, a compiler of sorts, a designer, and it has to appear somewhat attractive (styles). Of course, portability is high priority too. UE is made by lots of people. So remember that.

**Comment by textbrowser** [comment]
Builds in Mac, Windows, Raspbian, PowerPC, Debian, Ubuntu. Closing!
