### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by OsitoGrande** [textbrowser/glitch#8]
Hi, 
Unable to install latest APK from GitHub or F-Droid on Android 13 - "app incompatible with your phone". Pixel 7 Pro.
Regards,
Ian

**Comment by textbrowser** [comment]
I don't have an Android 13 so cannot test. Only 10.

**Comment by textbrowser** [comment]
Never mind.

**Comment by textbrowser** [comment]
![glitch](https://github.com/textbrowser/glitch/assets/10701156/c647263c-aef2-4c49-b624-59a73c68e519)

**Comment by textbrowser** [comment]
Maybe your device is ARM-64. As for F-DROID, Glitch isn't built for it. It's built for ARM-32 and Android 10. Works on 13 too.

**Comment by textbrowser** [comment]
I recommend a tablet and not a phone for Android. :)

**Comment by textbrowser** [comment]
Try https://github.com/textbrowser/glitch/releases/download/2023.07.30/Glitch-2023.07.30_arm64.apk.

**Comment by textbrowser** [comment]
Did you try arm64?

**Comment by textbrowser** [comment]
Silent person. Closing.
