### ISSUE TITLE
Release 2023.10.30_amd64.deb does not install required dependency libqt5pdfwidgets5

### ISSUE THREAD

**Issue by upost** [textbrowser/glitch#9]
I got this error after install when launching ./glitch.sh:

./Glitch: error while loading shared libraries: libQt5PdfWidgets.so.5: cannot open shared object file: No such file or directory

Then I did:

sudo apt-get install libqt5pdfwidgets5

Then it worked. 

System: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

**Comment by textbrowser** [comment]
I'm sorry. Did I mention I dislike packaging? And you're super correct. I'll need to correct the Debian control files to account for the PDF modules. This is difficult because qmake detects modules and the control files exist elsewhere and are not connected to the detection process. Thanks. :)
